language: java
git:
  submodules: false
install: true
script:
  - ./scripts/build.sh
  - ./scripts/test.sh
jdk:
  - oraclejdk8

before_deploy: ./scripts/prepare_deploy.sh

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: QNshVQLZ81QdFFlKqIplJG7W9MMpO5YO8Syk0R91kNXBIVy4EFCMWNjz9ejErb4RBp9aPv1XoyX9W4i+Mc1JQLFW4rahtaT02dsvk6rQcRE3ysGRVJYE7Ltui6t63wCwRxUYhL5F1sGULCXpDxHVGQSRFQnL/QVQx8ATMO/JXH2Q9rCbu20VktxcTcDUeJlbEEtlEdiqwlBuaESm2hDxSM5c2565t3u2ygvokohm6BUtLnvgH4LIqOUAVRiTUgsOgYVQuADn2RSs/iQ9TrBFWc1dZzcRjZH3XjSU95QOrFHPcIAN3VEQIoJ/rb6GvPdkkj8FJQtKOJepYy+gMywUnSEiWq9W/V7cr4IOVZ/4mTnfwazJzGdeKW7+g381SOy+nREzwV2sHwkCnFU2NAGxutHLF9sb2775d1l/LAmaJgCpXJwMYYXMcnzAIC3D1ofRFFkURgnVN+uvWyGWlauho109CSdxp5dZra85Ckj7q4YE0FsBMz0NMHq54HSOs5Fhxn8wghfwiMtYNoqxM6ekqPR7hR+RClQhdXYxdf4xUyxB/WzDDV/2dv4ESge1dY21Pwk/5gFXfXHUQQob9dSH0t3Uaoj1JDqIhJ/fICJTqx7mXT5ReD65rhmb0HucJnwPlxT/t9mYEswymY0u9xCFPzsukEzXi2+py1H0LnG6g8s=
  file:
   - maxeler-eclipse-plugin-$TRAVIS_TAG.tar.gz
   - maxeler-eclipse-plugin-$TRAVIS_TAG.zip
  on:
    repo: maxeler/eclipse
    branch: Luna-refactoring
    tags: true
