/*******************************************************************************
 * Copyright (c) 2000, 2013 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/**
 * IMPORTANT NOTE: These constants are dedicated to the internal Scanner implementation.
 * It is mirrored in org.eclipse.jdt.core.compiler public package where it is API.
 * The mirror implementation is using the backward compatible ITerminalSymbols constant
 * definitions (stable with 2.0), whereas the internal implementation uses TerminalTokens
 * which constant values reflect the latest parser generation state.
 */
/**
 * Maps each terminal symbol in the java-grammar into a unique integer.
 * This integer is used to represent the terminal when computing a parsing action.
 *
 * Disclaimer : These constant values are generated automatically using a Java
 * grammar, therefore their actual values are subject to change if new keywords
 * were added to the language (for instance, 'assert' is a keyword in 1.4).
 */
public interface TerminalTokens {

	// special tokens not part of grammar - not autogenerated
	int TokenNameNotAToken = 0,
		TokenNameWHITESPACE = 1000,
		TokenNameCOMMENT_LINE = 1001,
		TokenNameCOMMENT_BLOCK = 1002,
		TokenNameCOMMENT_JAVADOC = 1003;

	public final static int
    TokenNameIdentifier = 25,
    TokenNameabstract = 54,
    TokenNameassert = 75,
    TokenNameboolean = 103,
    TokenNamebreak = 76,
    TokenNamebyte = 104,
    TokenNamecase = 105,
    TokenNameCASE = 119,
    TokenNamecatch = 106,
    TokenNamechar = 107,
    TokenNameclass = 69,
    TokenNamecontinue = 77,
    TokenNameconst = 125,
    TokenNamedefault = 87,
    TokenNameOTHERWISE = 120,
    TokenNamedo = 78,
    TokenNamedouble = 108,
    TokenNameelse = 117,
    TokenNameELSE = 118,
    TokenNameenum = 72,
    TokenNameextends = 102,
    TokenNamefalse = 42,
    TokenNamefinal = 55,
    TokenNamefinally = 115,
    TokenNamefloat = 109,
    TokenNamefor = 79,
    TokenNamegoto = 126,
    TokenNameif = 80,
    TokenNameIF = 81,
    TokenNameimplements = 123,
    TokenNameimport = 110,
    TokenNameinstanceof = 12,
    TokenNameint = 111,
    TokenNameinterface = 71,
    TokenNamelong = 112,
    TokenNamenative = 56,
    TokenNamenew = 39,
    TokenNamenull = 43,
    TokenNamepackage = 101,
    TokenNameprivate = 57,
    TokenNameprotected = 58,
    TokenNamepublic = 59,
    TokenNamereturn = 82,
    TokenNameshort = 113,
    TokenNamestatic = 52,
    TokenNamestrictfp = 60,
    TokenNamesuper = 37,
    TokenNameswitch = 83,
    TokenNameSWITCH = 84,
    TokenNamesynchronized = 53,
    TokenNamethis = 38,
    TokenNamethrow = 85,
    TokenNamethrows = 121,
    TokenNametransient = 61,
    TokenNametrue = 44,
    TokenNametry = 86,
    TokenNamevoid = 114,
    TokenNamevolatile = 62,
    TokenNamewhile = 74,
    TokenNameIntegerLiteral = 45,
    TokenNameLongLiteral = 46,
    TokenNameFloatingPointLiteral = 47,
    TokenNameDoubleLiteral = 48,
    TokenNameCharacterLiteral = 49,
    TokenNameStringLiteral = 50,
    TokenNamePLUS_PLUS = 1,
    TokenNameMINUS_MINUS = 2,
    TokenNameEQUAL_EQUAL = 19,
    TokenNameEQUAL_EQUAL_EQUAL = 20,
    TokenNameLESS_EQUAL = 13,
    TokenNameGREATER_EQUAL = 14,
    TokenNameNOT_EQUAL = 21,
    TokenNameNOT_EQUAL_EQUAL = 22,
    TokenNameLEFT_SHIFT = 18,
    TokenNameRIGHT_SHIFT = 15,
    TokenNameUNSIGNED_RIGHT_SHIFT = 17,
    TokenNamePLUS_EQUAL = 89,
    TokenNameMINUS_EQUAL = 90,
    TokenNameMULTIPLY_EQUAL = 91,
    TokenNameDIVIDE_EQUAL = 92,
    TokenNameAND_EQUAL = 93,
    TokenNameOR_EQUAL = 94,
    TokenNameXOR_EQUAL = 95,
    TokenNameREMAINDER_EQUAL = 96,
    TokenNameLEFT_SHIFT_EQUAL = 97,
    TokenNameRIGHT_SHIFT_EQUAL = 98,
    TokenNameUNSIGNED_RIGHT_SHIFT_EQUAL = 99,
    TokenNameCONNECT = 100,
    TokenNameOR_OR = 34,
    TokenNameAND_AND = 33,
    TokenNamePLUS = 3,
    TokenNameMINUS = 4,
    TokenNameNOT = 66,
    TokenNameREMAINDER = 7,
    TokenNameXOR = 24,
    TokenNameAND = 23,
    TokenNameMULTIPLY = 6,
    TokenNameOR = 27,
    TokenNameTWIDDLE = 67,
    TokenNameDIVIDE = 8,
    TokenNameGREATER = 16,
    TokenNameLESS = 10,
    TokenNameLPAREN = 26,
    TokenNameRPAREN = 28,
    TokenNameLBRACE = 41,
    TokenNameRBRACE = 35,
    TokenNameLBRACKET = 11,
    TokenNameRBRACKET = 65,
    TokenNameSEMICOLON = 31,
    TokenNameQUESTION = 32,
    TokenNameCOLON = 63,
    TokenNameCOMMA = 36,
    TokenNameDOT = 5,
    TokenNameEQUAL = 73,
    TokenNameAT = 40,
    TokenNameELLIPSIS = 122,
    TokenNameHASH = 29,
    TokenNameARROW = 116,
    TokenNameCOLON_COLON = 9,
    TokenNameBeginLambda = 51,
    TokenNameBeginIntersectionCast = 68,
    TokenNameBeginTypeArguments = 88,
    TokenNameElidedSemicolonAndRightBrace = 70,
    TokenNameAT308 = 30,
    TokenNameAT308DOTDOTDOT = 124,
    TokenNameEOF = 64,
    TokenNameERROR = 127;
}
